[package]
name = "influx_db_client"
version = "0.4.1"
authors = ["piaoliu <441594700@qq.com>"]
documentation = "https://docs.rs/influx_db_client/"
repository = "https://github.com/driftluo/InfluxDBClient-rs"
description = "InfluxDB Rust driver"
readme = "README.md"
keywords = ["influxdb"]
categories = ["database"]
license = "MIT"
include = ["Cargo.toml", "src/*.rs", "README.md", "LICENSE"]
edition = "2018"

[badges]
travis-ci = { repository = "driftluo/InfluxDBClient-rs" }

[dependencies]
isahc = { version = "^0.9.3", features = ["json"] }
serde_json = '^1.0.2'
serde = { version = "^1.0.15", features = ["derive"] }
bytes = "^0.5"
futures = "^0.3"
url = "^2.1.1"
http = "^0.2.1"

[dev-dependencies]
tempdir = "0.3"
tokio = "0.2"
reqwest = "0.10.0"
async-std = "^1"
